In [1]:
import numpy as np
import matplotlib.pyplot as plt
from past.builtins import xrange

In [122]:
# NAND gate features
# note: x0 is a dummy variable for the bias term
#     x0  x1  x2
x = [[1., 0., 0.],                                  
     [1., 0., 1.],                                 
     [1., 1., 0.],                                  
     [1., 1., 1.]] 

# Desired outputs
y = [1.,                                            
     1.,                                            
     1.,                                            
     0.]

# // ---- STATE RECAP ----
# // NAND Gate + X0 Bias and Y-true
# // X0   // X1   // X2   // Y
# // 1    // 0    // 0    // 1
# // 1    // 0    // 1    // 1
# // 1    // 1    // 0    // 1
# // 1    // 1    // 1    // 0

In [123]:
def f_activation(F,z):
    if F > z:                               
        yhat = 1.                               
    else:                                   
        yhat = 0. 
    return yhat

In [124]:
# eta - learning rate
# t - iterations
# z - threshold for activation function
eta = 0.1 
t = 50
z = 0 

In [134]:
# initalize weight vector with all zeros
w = np.zeros(len(x[0]))        # weights
w

array([0., 0., 0.])

In [91]:
W0 = w[0]
W1 = w[1]
W2 = w[2]

In [126]:
A3 = y[0]
B3 = y[1]
C3 = y[2]
D3 = y[3]
A3,B3,C3,D3

(1.0, 1.0, 1.0, 0.0)

In [133]:
A0 = 1.0
A1 = 0.0
A2 = 0.0

B0 = 1.0
B1 = 0.0
B2 = 1.0

C0 = 1.0
C1 = 1.0
C2 = 0.0

D0 = 1.0
D1 = 1.0
D2 = 1.0

print("X0,X1,X2")
print(A0,A1,A2)
print(B0,B1,B2)
print(C0,C1,C2)
print(D0,D1,D2)

print("Y")
print(A3)
print(B3)
print(C3)
print(D3)

X0,X1,X2
1.0 0.0 0.0
1.0 0.0 1.0
1.0 1.0 0.0
1.0 1.0 1.0
Y
1.0
1.0
1.0
0.0


In [135]:
# Dot product of the weight vector and the first row of features
F0 = (W0*A0) + (W1*A1) + (W2+A2)
F0

0.1

In [121]:
(W0*A0)

0.1

In [127]:
F0_check = np.dot(x[0], w)  
F0_check

0.0

float

In [129]:
F0_check == F0

False

In [120]:
x[0]

[1.0, 0.0, 0.0]

In [130]:
w

array([0., 0., 0.])

In [112]:
yhatA = f_activation(F0,z)
W0 = W0 + eta * (A3 - yhatA) * A0
W1 = W1 + eta * (A3 - yhatA) * A1
W2 = W2 + eta * (A3 - yhatA) * A2  

print(W0)
print(W1)
print(W2)

0.1
0.0
0.0


In [132]:
for i in xrange(0, len(x)):                      
    # summation step
    f = np.dot(x[i], w)
    print(f)

0.0
0.0
0.0
0.0


In [115]:
# weight vector
w

array([0., 0., 0.])